# Generated by Django 4.2.23 on 2026-04-22 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='renewal_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'category'], name='hello_docum_user_id_d96c78_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['renewal_date'], name='hello_docum_renewal_22b427_idx'),
        ),
    ]
